### ISSUE TITLE
Saving likelihoods printed to screen

### ISSUE THREAD

**Issue by Mark-McCann** [luca-marotta/biSBMR#1] opened 2020-02-29 17:52 UTC
Hi, 
I've got biSBM running in R but having difficulty saving stats. The model parameters and stats aren't saved in the object biSBM creates, and I can't get the numbers from the console with sink() either.  

The rest of the model output appears in the sink() file, but the likelihood scores appear on screen in RStudio without being directed to sink(). 

Any tweaks to biSBM, or advice on workarounds would be much appreciated.

Thanks,
  Mark 

Ps. Console output

> loc <- "sbmll.txt"
> sink(loc, append = F)
> sink(type = "message")
> sbm.object <- biSBM(data = el, nodeType = types, ka = 2, kb = 3, deg.corr = 1, iter = 10)
>1, 1, -5126.23
>2, 1, -5115.83
>3, 1, -5115.83
>4, 1, -5105.87
>5, 1, -5105.87
>6, 1, -5105.87
>7, 1, -5105.87
>8, 1, -5105.87
>9, 1, -5105.87
>10, 1, -5095.51
Final Score: -5095.51
> sink()
> sink(type = "message")
> txt <- readLines("sbmll.txt")
> txt
 [1] "KA 2"                                         "KB 3"                                        
 [3] ""                                             "Calling biSBM with the following parameters."
 [5] "KA:\t2"                                        "KB:\t3"                                       
 [7] "NA:\t303"                                      "NB:\t16"                                      
 [9] "Type A Communities: 1,2,"                     "Type B Communities: 3,4,5,"                  
[11] "DegreeCorrect:\t1"                             "Edges:\t788"                                  
> sbm.object 
  [1] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1
 [48] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 2 1 1 1 1 2 1 1 1 1 2 1 1 1 1
 [95] 1 1 1 1 1 1 2 1 1 2 1 1 2 2 1 2 1 2 1 2 1 1 2 1 1 1 2 1 2 2 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 2 2
[142] 2 2 1 2 1 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 2 2 1 2 2 2 2 2 2 2 1 1 1 1 2
[189] 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2
[236] 2 2 2 2 1 2 1 1 1 2 2 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 1 1 1 2 1 2 2 2 2 2 2 1 2 2
[283] 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 2 2 2 2 2 2 4 4 3 3 3 5 5 3 5 5 3 5 4 3 3 5

**Comment by luca-marotta** [comment] 2020-04-05 02:41
Hi Mark, 
sorry for the delay, I didn't check the repo for a while. 
I just pushed a new version of the header files that should address your issue. Now, if you sink the output,  the model statistics should be included. 

Btw, which OS are you using? I only have a Linux system available, therefore I could not test the solution on Windows.

Let me know if the issue is solved. However, the easiest way to capture all the output is to run your R script from the command line (using the **Rscript** command) and redirect the output to a file. In that way you can be sure all the output will be captured.

Thanks, 
Luca

**Comment by andrewbaxter439** [comment] 2020-04-07 15:33
Hi Luca, have been testing on Windows and was working on same problem as Mark. Tested your recent version but the header file hasn't been edited? still giving same output.

I'd been working on a solution to this that I've put in a fork - https://github.com/andrewbaxter439/biSBMR

Essentially this passes the `MaxScore`  argument back to the `.C` call in R, then the Rscript creates an object with the groupings and the score (with a new `print.biSBM` function below to display the output tidily). Have only edited windows files. Do ignore if this is all duplicating your already written fixes.

Thanks for the work on the package as well, very useful!

**Comment by Mark-McCann** [comment] 2020-04-07 15:39
Hi Luca,

                No problem on the delay, we found a workaround to get the fit stats in the meantime. I’m using R 3.6.3 in Windows 10. That’s a good idea on running in batch mode, thanks.

I’ve just checked the repo but the latest commit doesn’t seem to include these changes. Can you double check the commit?

As an addition to the original request, it would be great if the final score was stored as part of the sbm.object, as this would allow us to compare the fit of various models within R, rather than having to load the stats from a sunk output file.

                Many thanks,
                                Mark

**Comment by luca-marotta** [comment] 2020-04-07 17:04
Hi Mark, Andrew

I committed again. Now the new headers should be the correct ones. I guess that's what you get for pushing changes at 5 am on a Saturday night. 

Please take a look. 
@Mark-McCann: seems what you're asking is what @andrewbaxter439 talks about in his comment. 
Let me see what's the best way to do this and then I can either integrate @andrewbaxter439 's changes or use them as a basis to add the score to the final output. 

Thank you both for your feedback!

**Comment by andrewbaxter439** [comment] 2020-04-08 09:14
Hi @luca-marotta - have tested out your new update on Windows and it's working to send the `Rcout` calls to `sink`:
```
> loc <- "sbmll.txt"
> sink(loc, append = F)
> sink(type = "message")
> ##### TEST 1 - Southern Women #####
> edges <- read.table("southernWomen.edgelist");  ## edgelist
> types <- read.table("southernWomen.types");     ## nodeType
> ### call to the function: by default deg.corr=1 and iter = 10.
> g <- biSBM(data = edges, nodeType = types, ka = 2, kb = 3, deg.corr = 1, iter = 3);
> sink()
> sink(type = "message")
> txt <- readLines("sbmll.txt")
> txt
 [1] "KA 2"                                         "KB 3"                                        
 [3] ""                                             "Calling biSBM with the following parameters."
 [5] "KA:\t2"                                        "KB:\t3"                                       
 [7] "NA:\t18"                                       "NB:\t14"                                      
 [9] "Type A Communities: 1,2,"                     "Type B Communities: 3,4,5,"                  
[11] "DegreeCorrect:\t1"                             "Edges:\t89"                                   
[13] ">1, 0, -367.658"                              ">2, 0, -367.658"                             
[15] ">3, 0, -367.658"                              "Final Score: -367.658" 
```

Calling `Rscript example_R.R > output.txt` from command line works too - both helpful tricks I now have in my back pocket 😄.

**Comment by luca-marotta** [comment] 2020-04-12 20:31
Hi @andrewbaxter439, @Mark-McCann, 

I just pushed a new revision that defines a biSBMObj class, together with a constructor and a few generic methods: 
   * **summary** to get some basic info about the object. It is inspired by @andrewbaxter439's print function but provides different information. For example, the nodes of the original network are grouped in a list based on the partition they belong. 
   *  **getPartition** to get the vector indicating the partition each node belongs to, i.e. the vector returned by the previous version of the code. 
   * **getScore** returns the final likelihood score.

I'm going to close this issue, as now the relevant output can be sunk. If there's some problem with the new class, don't hesitate to open a separate issue. 

Thanks,  
Luca

**Closed as completed by luca-marotta** 2020-04-12 20:31 UTC

**Comment by andrewbaxter439** [comment] 2020-04-21 22:03
Hi @luca-marotta, thanks for this! Sorry for the delay in getting to try this out, new output is fab and really useful!
